### ISSUE TITLE
Issue when Disallow: / does not end with a space

### ISSUE THREAD

**Issue by rbedfordpro** [b4dnewz/robots-parse#4]
"Disallow: / "   <--- works as expected
vs
"Disallow: /"   <--- does not properly parse

For a workaround I added:
@line 33:
    if (!line.endsWith(' ')){
      line = line+" "
    }

**Comment by b4dnewz** [comment]
it should be already fixed with one of the last commits, see [this line](https://github.com/b4dnewz/robots-parse/blob/master/src/parser.ts#L39)
